// auto-generated by executing generate.sh/.bat (protoc/.exe) on ../proto/complexmessage.proto

package complexpb // use option go_package = "complexpb"; in complexmessage.proto, before compiling

// ...